name: Dupe Plugin
version: 1
main: me.anup.dupe.Plugin
api-version: 1.8.9
description: Minecraft Dupe plugin
commands:
  heal:
    description: heals player to max health
    usage: /<command>
    aliases: heal
  feed:
    description: makes players saturation 20
    usage: /<command>
    aliases: feed
  dupe:
    description: dupes item
    usage: /<command>
    aliases: [dupe, d]

